"""Quantum Natural Gradient (QNG).

In classical machine learning, the "natural gradient" replaces vanilla
gradient descent θ ← θ - η ∇L with

    θ ← θ - η · F⁻¹ ∇L

where F is the Fisher information matrix. This rescales steps by the
information geometry, often dramatically accelerating convergence.

The QUANTUM natural gradient (Stokes-Izaac-Killoran-Carleo 2020)
generalizes this for parameterized quantum circuits |ψ(θ)⟩:

    F_ij(θ) = Re ⟨∂_i ψ | ∂_j ψ⟩  -  Re ⟨∂_i ψ | ψ⟩⟨ψ | ∂_j ψ⟩

(the Fubini-Study metric). The update is:

    θ ← θ - η · F⁻¹ ∇⟨H⟩

For a hardware-efficient ansatz with single-qubit rotations and CNOT
entanglers, ∂_i |ψ⟩ has a clean closed form via parameter-shift
gradients.

This module provides:

  - `fubini_study_metric(states_at_shifts)`: build F from shifted
    state vectors.
  - `quantum_natural_gradient_step(loss_fn, params, ansatz_apply,
      n_params, lr, lambda_reg)`: one QNG step.
  - `train_with_qng(...)`: full training loop.

QNG often gives 5–20x convergence acceleration vs vanilla gradient
descent for typical VQE problems.
"""

from __future__ import annotations

from typing import Callable

import numpy as np


# ----------------------------------------------------------------------------
# Fubini-Study metric construction
# ----------------------------------------------------------------------------

def state_derivative(
    ansatz_apply: Callable[[np.ndarray, np.ndarray], np.ndarray],
    params: np.ndarray,
    ref_state: np.ndarray,
    param_idx: int,
    shift: float = np.pi / 2,
) -> np.ndarray:
    """Compute ∂|ψ(θ)⟩/∂θ_i via the parameter-shift rule.

    For a single Pauli rotation R(θ) = exp(-i θ/2 σ):
        R(θ + s) - R(θ - s) = -2 sin(s/2) · (sin(θ/2) I + i cos(θ/2) σ)
        ∂R/∂θ              = -1/2 · (sin(θ/2) I + i cos(θ/2) σ)

    so
        |ψ(θ+s)⟩ - |ψ(θ-s)⟩  =  4 sin(s/2) · ∂|ψ⟩/∂θ
        ∂|ψ⟩/∂θ              =  (|ψ+⟩ - |ψ-⟩) / (4 sin(s/2))

    Default s = π/2 → divisor = 4 sin(π/4) = 2√2.
    """
    p_plus = params.copy()
    p_plus[param_idx] += shift
    p_minus = params.copy()
    p_minus[param_idx] -= shift
    psi_plus = ansatz_apply(p_plus, ref_state)
    psi_minus = ansatz_apply(p_minus, ref_state)
    return (psi_plus - psi_minus) / (4 * np.sin(shift / 2))


def fubini_study_metric(
    ansatz_apply: Callable[[np.ndarray, np.ndarray], np.ndarray],
    params: np.ndarray,
    ref_state: np.ndarray,
) -> np.ndarray:
    """Build the Fubini-Study metric matrix:

        F_ij = Re ⟨∂_i ψ | ∂_j ψ⟩  -  Re ⟨∂_i ψ | ψ⟩⟨ψ | ∂_j ψ⟩

    Args:
        ansatz_apply:  callable (params, ref) → state vector.
        params:        current parameter vector.
        ref_state:     reference state.

    Returns:
        n_params × n_params real PSD matrix.
    """
    n_params = len(params)
    psi = ansatz_apply(params, ref_state)
    derivs = [state_derivative(ansatz_apply, params, ref_state, k)
              for k in range(n_params)]
    overlaps = np.array([np.vdot(psi, d) for d in derivs], dtype=np.complex128)
    F = np.zeros((n_params, n_params), dtype=np.float64)
    for i in range(n_params):
        for j in range(n_params):
            inner = np.vdot(derivs[i], derivs[j])
            F[i, j] = float(np.real(inner) - np.real(overlaps[i].conj() * overlaps[j]))
    # Symmetrize numerically.
    F = 0.5 * (F + F.T)
    return F


# ----------------------------------------------------------------------------
# Gradient + QNG step
# ----------------------------------------------------------------------------

def parameter_shift_gradient(
    loss_fn: Callable[[np.ndarray], float],
    params: np.ndarray,
    shift: float = np.pi / 2,
) -> np.ndarray:
    """Compute ∇L(θ) via the parameter-shift rule.

    Assumes loss_fn(params) = ⟨H⟩ where the state is generated by an
    ansatz built from Pauli-rotation gates. The shift rule gives:

        ∂L/∂θ_i = [L(θ + s) - L(θ - s)] / 2  for s = π/2.
    """
    n = len(params)
    grad = np.zeros(n)
    for i in range(n):
        p_plus = params.copy(); p_plus[i] += shift
        p_minus = params.copy(); p_minus[i] -= shift
        grad[i] = (loss_fn(p_plus) - loss_fn(p_minus)) / 2.0
    return grad


def quantum_natural_gradient_step(
    loss_fn: Callable[[np.ndarray], float],
    ansatz_apply: Callable[[np.ndarray, np.ndarray], np.ndarray],
    params: np.ndarray,
    ref_state: np.ndarray,
    lr: float = 0.1,
    lambda_reg: float = 1e-3,
) -> tuple[np.ndarray, dict]:
    """One QNG update step.

    Args:
        loss_fn:       L(params) — the scalar to minimize.
        ansatz_apply:  (params, ref) → state vector.
        params:        current parameter vector.
        ref_state:     reference for the ansatz.
        lr:            learning rate.
        lambda_reg:    regularization for F⁻¹ (Tikhonov).

    Returns:
        (new_params, diagnostics dict).
    """
    n = len(params)
    F = fubini_study_metric(ansatz_apply, params, ref_state)
    g = parameter_shift_gradient(loss_fn, params)
    # Regularized inverse: (F + λI)⁻¹ g.
    F_reg = F + lambda_reg * np.eye(n)
    step = np.linalg.solve(F_reg, g)
    new_params = params - lr * step
    return new_params, {
        "F": F, "gradient": g, "step": step,
        "loss":   loss_fn(params),
        "loss_new": loss_fn(new_params),
    }


# ----------------------------------------------------------------------------
# Full training loop
# ----------------------------------------------------------------------------

def train_with_qng(
    loss_fn: Callable[[np.ndarray], float],
    ansatz_apply: Callable[[np.ndarray, np.ndarray], np.ndarray],
    init_params: np.ndarray,
    ref_state: np.ndarray,
    n_iter: int = 50,
    lr: float = 0.1,
    lambda_reg: float = 1e-3,
    tol: float = 1e-6,
) -> dict:
    """Run QNG until convergence.

    Returns:
        dict with optimized params, loss history, convergence flag.
    """
    params = np.asarray(init_params, dtype=np.float64).copy()
    loss_history = [loss_fn(params)]
    for it in range(n_iter):
        params, info = quantum_natural_gradient_step(
            loss_fn, ansatz_apply, params, ref_state, lr=lr,
            lambda_reg=lambda_reg,
        )
        loss_history.append(info["loss_new"])
        if abs(loss_history[-1] - loss_history[-2]) < tol:
            return {
                "params":      params,
                "loss":        loss_history[-1],
                "loss_history": loss_history,
                "converged":   True,
                "n_iter":      it + 1,
            }
    return {
        "params":      params,
        "loss":        loss_history[-1],
        "loss_history": loss_history,
        "converged":   False,
        "n_iter":      n_iter,
    }
