"""Single-qubit randomized benchmarking (RB) — Knill et al. 2008.

The canonical NISQ hardware-characterization protocol:

  1. Generate a random sequence of m Clifford gates: C_1, C_2, ..., C_m.
  2. Compute the inverse Clifford C_inv = (C_m · ... · C_1)^{-1}.
  3. Apply C_1, C_2, ..., C_m, C_inv to |0⟩, with noise after each gate.
  4. In the *ideal* case, the final state is |0⟩ (so measurement of qubit
     gives 0 with probability 1). With noise, P(0) decays with m.
  5. Fit P(0) vs m to A · p^m + B, where p is the average gate fidelity
     parameter. The average gate error per Clifford is r = (1-p)/2.

Because the Clifford group is a unitary 2-design, the noisy fidelity decay
depends *only on the average gate error*, not on the specific gates -- this
is why RB is a gate-independent characterization protocol.

We implement the single-qubit case (Clifford group of 24 elements). Two-qubit
RB exists but the Clifford group has 11520 elements; multi-qubit RB is
typically delegated to specialized libraries.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from ..circuit import QuantumCircuit
from ..gates import H, S, I2, X, Y, Z
from ..noise import apply_channel_trajectory


# ---- the 24-element single-qubit Clifford group ----

def _build_single_qubit_clifford_group() -> list[np.ndarray]:
    """Enumerate all 24 single-qubit Cliffords as 2x2 unitaries.

    The single-qubit Clifford group is generated by {H, S}. We enumerate
    by BFS over compositions and collect distinct unitaries (up to global
    phase) until we have all 24.
    """
    Sdg = np.array([[1, 0], [0, -1j]], dtype=np.complex128)
    generators = {"H": H, "S": S, "Sdg": Sdg}
    cliffords: list[np.ndarray] = [np.eye(2, dtype=np.complex128)]

    def _eq_up_to_phase(A, B, tol=1e-9):
        # Find any nonzero entry of A and rescale B.
        for i in range(2):
            for j in range(2):
                if abs(A[i, j]) > tol:
                    phase = A[i, j] / B[i, j] if abs(B[i, j]) > tol else None
                    if phase is None:
                        return False
                    return np.allclose(A, phase * B, atol=tol)
        return False

    def _already_present(U):
        for V in cliffords:
            if _eq_up_to_phase(U, V):
                return True
        return False

    frontier = [np.eye(2, dtype=np.complex128)]
    while frontier and len(cliffords) < 24:
        next_frontier = []
        for U in frontier:
            for G in generators.values():
                V = G @ U
                if not _already_present(V):
                    cliffords.append(V)
                    next_frontier.append(V)
        frontier = next_frontier
    return cliffords


_CLIFFORDS = _build_single_qubit_clifford_group()


def random_single_qubit_clifford(rng: np.random.Generator) -> np.ndarray:
    """Sample one of the 24 single-qubit Cliffords uniformly at random."""
    idx = int(rng.integers(0, len(_CLIFFORDS)))
    return _CLIFFORDS[idx].copy()


def _inverse_clifford(U: np.ndarray) -> np.ndarray:
    """Return U^{-1} = U^† (Cliffords are unitary)."""
    return U.conj().T


# ---- the RB experiment ----

@dataclass
class RBResult:
    sequence_lengths: np.ndarray
    survival_probabilities: np.ndarray
    p_fit: float                  # decay parameter
    A_fit: float                  # amplitude
    B_fit: float                  # offset
    average_gate_error: float     # r = (1 - p) / 2 for single qubit

    def __repr__(self) -> str:
        return (f"RBResult(p={self.p_fit:.6f}, "
                f"r={self.average_gate_error:.4e}, "
                f"lengths={self.sequence_lengths.tolist()})")


def run_rb_sequence(
    n_gates: int,
    kraus_per_gate: list[np.ndarray] | None,
    rng: np.random.Generator,
) -> int:
    """Run a single RB sequence of length n_gates and return the measurement
    outcome (0 or 1).

    `kraus_per_gate`: a single-qubit Kraus-operator list applied AFTER each
    gate (including the recovery gate). If None, no noise is applied.
    """
    qc = QuantumCircuit(1)
    composed = np.eye(2, dtype=np.complex128)
    for _ in range(n_gates):
        C = random_single_qubit_clifford(rng)
        qc.apply_unitary(C, [0], check_unitary=False)
        composed = C @ composed
        if kraus_per_gate is not None:
            qc.state = apply_channel_trajectory(
                qc.state, kraus_per_gate, 0, 1, rng
            )
    # Recovery gate: the unitary that undoes everything.
    R = _inverse_clifford(composed)
    qc.apply_unitary(R, [0], check_unitary=False)
    if kraus_per_gate is not None:
        qc.state = apply_channel_trajectory(
            qc.state, kraus_per_gate, 0, 1, rng
        )
    # Measure.
    outcome = int(qc.measure_all(shots=1, rng=rng)[0])
    return outcome


def randomized_benchmarking(
    sequence_lengths: list[int],
    kraus_per_gate: list[np.ndarray] | None,
    n_trials: int = 100,
    rng: np.random.Generator | None = None,
) -> RBResult:
    """Run a full randomized-benchmarking experiment.

    Args:
        sequence_lengths: list of gate-sequence lengths m to test.
        kraus_per_gate:   the noise channel applied after each gate. None
                          for noise-free.
        n_trials:         number of random sequences per length (for averaging).
        rng:              numpy generator.

    Returns:
        RBResult with the fitted decay parameter p, gate error r = (1-p)/2,
        and the raw survival-probability data.
    """
    rng = rng or np.random.default_rng()
    lengths = np.array(sorted(set(sequence_lengths)), dtype=int)
    survivals: list[float] = []
    for m in lengths:
        zeros = 0
        for _ in range(n_trials):
            if run_rb_sequence(int(m), kraus_per_gate, rng) == 0:
                zeros += 1
        survivals.append(zeros / n_trials)
    survivals_arr = np.array(survivals, dtype=np.float64)

    # Fit P(0; m) = A · p^m + B. We solve a small nonlinear least squares
    # via log-linearization first, then a Levenberg-Marquardt refinement.
    p_fit, A_fit, B_fit = _fit_rb_decay(lengths, survivals_arr)
    r = max(0.0, (1.0 - p_fit) / 2.0)

    return RBResult(
        sequence_lengths=lengths,
        survival_probabilities=survivals_arr,
        p_fit=p_fit, A_fit=A_fit, B_fit=B_fit,
        average_gate_error=r,
    )


def _fit_rb_decay(lengths: np.ndarray, survivals: np.ndarray
                  ) -> tuple[float, float, float]:
    """Fit survivals ≈ A · p^m + B."""
    from scipy.optimize import curve_fit

    def model(m, A, p, B):
        return A * np.power(p, m) + B

    # Reasonable starting guesses.
    p_init = max(0.5, (survivals[-1] - 0.5) / (survivals[0] - 0.5 + 1e-9))
    p_init = min(max(p_init, 0.5), 0.999)
    A_init = max(survivals[0] - 0.5, 0.1)
    B_init = 0.5
    try:
        popt, _ = curve_fit(
            model, lengths.astype(float), survivals.astype(float),
            p0=(A_init, p_init, B_init),
            bounds=([-1.0, 0.0, 0.0], [1.5, 1.0, 1.0]),
            maxfev=5000,
        )
        A, p, B = popt
        return float(p), float(A), float(B)
    except Exception:
        # Fallback: just report p as zero (no useful decay observed).
        return 1.0, 1.0, 0.0
