"""Stabilizer-formalism simulation of Clifford circuits.

Gottesman's theorem: any quantum state stabilized by a set of N commuting
Pauli operators (a "stabilizer state") is uniquely determined by those N
generators. The Clifford group (generated by {H, S, CNOT}) maps stabilizer
states to stabilizer states, with each gate updating each generator in O(N)
work. So a circuit of D Clifford gates on N qubits runs in O(N²D) time
instead of the O(2^N · D) dense path -- **polynomial scaling, full stop**.

Coverage:
    - Universal gates among Cliffords: H, S, CNOT (and derived X, Y, Z, CZ, SWAP)
    - Z-basis measurement with correct random/deterministic dispatch
    - Arbitrary-N: trivially handles 10,000 qubits where the dense engine
      caps out at ~28

Not covered (Clifford circuits are NOT universal):
    - T gate / non-Clifford rotations
    - Most "interesting" quantum algorithms (Shor, Grover-with-non-Pauli-oracle)
    - Real-valued continuous rotations Rx, Ry, Rz at arbitrary angles

What stabilizer sims ARE used for in practice:
    - Quantum error correction (surface code, repetition code, toric code)
    - Magic-state distillation
    - Verifying quantum circuit equivalence on the Clifford subset
    - Benchmarking decoders at huge system sizes

Reference: Aaronson & Gottesman, "Improved Simulation of Stabilizer
Circuits", Phys. Rev. A 70, 052328 (2004).

Tableau representation: a (2N+1) x (2N+1) bit array.
    rows 0     .. N-1   : destabilizer generators
    rows N     .. 2N-1  : stabilizer generators
    row  2N             : scratch (used during deterministic measurement)
    cols 0     .. N-1   : X-component bits of each Pauli
    cols N     .. 2N-1  : Z-component bits of each Pauli
    col  2N             : sign bit (0 -> +, 1 -> -)
"""

from __future__ import annotations

import numpy as np


class StabilizerState:
    """Stabilizer state on N qubits, evolved under Clifford gates in poly time."""

    def __init__(self, n: int):
        if n < 1:
            raise ValueError("need at least 1 qubit")
        self.n = n
        # (2N+1) x (2N+1) -- one extra row for scratch, one extra column for sign.
        self.tab = np.zeros((2 * n + 1, 2 * n + 1), dtype=np.int8)
        # |0...0>: destabilizer i = X_i, stabilizer i = Z_i.
        for i in range(n):
            self.tab[i, i] = 1
            self.tab[n + i, n + i] = 1
        self.history: list[str] = []

    # ---- Clifford gates ----------------------------------------------------
    #
    # Each Clifford gate is implemented as a constant-depth bit update across
    # all 2N generator rows. The phase-tracking rules come from the conjugation
    # action of each gate on the four Pauli operators.

    def h(self, q: int) -> "StabilizerState":
        """Hadamard: X <-> Z. Phase flips wherever the row had a Y (x=z=1)."""
        n = self.n
        self._check_q(q)
        x = self.tab[:, q].copy()
        z = self.tab[:, n + q].copy()
        self.tab[:, 2 * n] ^= x & z
        self.tab[:, q] = z
        self.tab[:, n + q] = x
        self.history.append(f"H({q})")
        return self

    def s(self, q: int) -> "StabilizerState":
        """Phase gate S: maps X -> Y, Y -> -X, Z -> Z."""
        n = self.n
        self._check_q(q)
        x = self.tab[:, q]
        z = self.tab[:, n + q]
        self.tab[:, 2 * n] ^= x & z
        self.tab[:, n + q] ^= x
        self.history.append(f"S({q})")
        return self

    def sdg(self, q: int) -> "StabilizerState":
        """S-dagger: inverse of S. S three times equals S^-1."""
        self.s(q); self.s(q); self.s(q)
        self.history.append(f"Sdg({q})")
        return self

    def x(self, q: int) -> "StabilizerState":
        """Pauli X: conjugation flips sign of any Z-bearing generator (X anticommutes with Z)."""
        self._check_q(q)
        self.tab[:, 2 * self.n] ^= self.tab[:, self.n + q]
        self.history.append(f"X({q})")
        return self

    def z(self, q: int) -> "StabilizerState":
        """Pauli Z: flips sign of any X-bearing generator."""
        self._check_q(q)
        self.tab[:, 2 * self.n] ^= self.tab[:, q]
        self.history.append(f"Z({q})")
        return self

    def y(self, q: int) -> "StabilizerState":
        """Pauli Y = iXZ: flips sign of generators bearing exactly one of X, Z (not Y, not I)."""
        n = self.n
        self._check_q(q)
        self.tab[:, 2 * n] ^= self.tab[:, q] ^ self.tab[:, n + q]
        self.history.append(f"Y({q})")
        return self

    def cnot(self, a: int, b: int) -> "StabilizerState":
        """CNOT control a, target b.

        Action on generators:
            X_a -> X_a X_b ;  Z_b -> Z_a Z_b ;  others fixed.
        """
        n = self.n
        self._check_q(a); self._check_q(b)
        if a == b:
            raise ValueError("control and target must differ")
        xa = self.tab[:, a].copy()
        za = self.tab[:, n + a].copy()
        xb = self.tab[:, b].copy()
        zb = self.tab[:, n + b].copy()
        self.tab[:, 2 * n] ^= xa & zb & (xb ^ za ^ 1)
        self.tab[:, b] ^= xa
        self.tab[:, n + a] ^= zb
        self.history.append(f"CNOT({a},{b})")
        return self

    def cz(self, a: int, b: int) -> "StabilizerState":
        """CZ = (I⊗H) · CNOT · (I⊗H)."""
        self.h(b); self.cnot(a, b); self.h(b)
        self.history.append(f"CZ({a},{b})")
        return self

    def swap(self, a: int, b: int) -> "StabilizerState":
        """SWAP via three CNOTs."""
        self.cnot(a, b); self.cnot(b, a); self.cnot(a, b)
        self.history.append(f"SWAP({a},{b})")
        return self

    # ---- measurement -------------------------------------------------------

    def measure(self, q: int, rng: np.random.Generator | None = None,
                force: int | None = None) -> int:
        """Measure qubit `q` in the Z basis. Returns 0 or 1; state collapses.

        If `force` is 0 or 1 and the outcome is random, that value is used
        (useful for deterministic tests). For deterministic outcomes the
        force argument is ignored -- the algorithm computes the unique value.
        """
        n = self.n
        self._check_q(q)
        # Find any stabilizer with X-bit at column q == 1 => measurement is random.
        p = -1
        for i in range(n, 2 * n):
            if self.tab[i, q]:
                p = i
                break

        if p >= 0:
            # Random outcome: respect `force` if given, else sample.
            if force is not None:
                outcome = int(force)
            elif rng is not None:
                outcome = int(rng.integers(0, 2))
            else:
                outcome = int(np.random.randint(0, 2))
            # For every other row with X-bit at q == 1: rowsum(i, p).
            # Skip i = p - n (the destabilizer partner of the pivot stabilizer):
            # it would attempt to rowsum two anticommuting rows, AND it gets
            # overwritten in the next step anyway, so the work would be wasted.
            partner = p - n
            for i in range(2 * n):
                if i != p and i != partner and self.tab[i, q]:
                    self._rowsum(i, p)
            # Promote old stabilizer row p to destabilizer row (p - n).
            self.tab[p - n, :] = self.tab[p, :]
            # Replace row p with the measured Pauli: ±Z_q.
            self.tab[p, :] = 0
            self.tab[p, n + q] = 1
            self.tab[p, 2 * n] = outcome
            return outcome
        else:
            # Deterministic outcome. Use scratch row 2n.
            self.tab[2 * n, :] = 0
            for i in range(n):
                if self.tab[i, q]:
                    self._rowsum(2 * n, i + n)
            return int(self.tab[2 * n, 2 * n])

    def _rowsum(self, h: int, i: int) -> None:
        """Row h <- row h * row i (Pauli multiplication, with phase tracking)."""
        n = self.n
        # Phase update via accumulator mod 4.
        x1 = self.tab[i, :n].astype(np.int32)
        z1 = self.tab[i, n:2 * n].astype(np.int32)
        x2 = self.tab[h, :n].astype(np.int32)
        z2 = self.tab[h, n:2 * n].astype(np.int32)

        g = np.zeros(n, dtype=np.int32)
        case10 = (x1 == 1) & (z1 == 0)
        case01 = (x1 == 0) & (z1 == 1)
        case11 = (x1 == 1) & (z1 == 1)
        # g(1, 0, x2, z2) = z2 * (2*x2 - 1)
        g[case10] = z2[case10] * (2 * x2[case10] - 1)
        # g(0, 1, x2, z2) = x2 * (1 - 2*z2)
        g[case01] = x2[case01] * (1 - 2 * z2[case01])
        # g(1, 1, x2, z2) = z2 - x2
        g[case11] = z2[case11] - x2[case11]

        acc = 2 * int(self.tab[h, 2 * n]) + 2 * int(self.tab[i, 2 * n]) + int(g.sum())
        acc %= 4
        if acc == 0:
            self.tab[h, 2 * n] = 0
        elif acc == 2:
            self.tab[h, 2 * n] = 1
        else:                                           # pragma: no cover
            raise RuntimeError(f"rowsum acc={acc}, expected 0 or 2 mod 4")

        self.tab[h, :n] ^= self.tab[i, :n]
        self.tab[h, n:2 * n] ^= self.tab[i, n:2 * n]

    # ---- inspection --------------------------------------------------------

    def stabilizers(self) -> list[str]:
        """Stabilizer generators as readable Pauli strings (e.g. '+XXII', '-ZZII')."""
        return [self._row_to_string(i) for i in range(self.n, 2 * self.n)]

    def destabilizers(self) -> list[str]:
        return [self._row_to_string(i) for i in range(self.n)]

    def _row_to_string(self, row: int) -> str:
        n = self.n
        chars = []
        for q in range(n):
            x = int(self.tab[row, q]); z = int(self.tab[row, n + q])
            chars.append({(0, 0): "I", (1, 0): "X", (0, 1): "Z", (1, 1): "Y"}[(x, z)])
        sign = "-" if self.tab[row, 2 * n] else "+"
        return sign + "".join(chars)

    def tableau_storage_bytes(self) -> int:
        return self.tab.nbytes

    # ---- Pauli expectation values ------------------------------------------

    def pauli_expectation(self, pauli_string: str) -> int:
        """Return ⟨ψ|P|ψ⟩ for a Pauli string P on the current stabilizer state.

        Returns one of {-1, 0, +1}. For stabilizer states this expectation is
        always integer-valued:
            +1 if +P is in the stabilizer group,
            -1 if -P is in the stabilizer group,
             0 if P anticommutes with some stabilizer.

        `pauli_string` is N characters from {'I', 'X', 'Y', 'Z'}.
        """
        if len(pauli_string) != self.n:
            raise ValueError(f"need {self.n}-char Pauli string, got {len(pauli_string)}")
        n = self.n
        # Encode the candidate as bit vectors.
        x_bits = np.zeros(n, dtype=np.int8)
        z_bits = np.zeros(n, dtype=np.int8)
        for q, ch in enumerate(pauli_string.upper()):
            if ch == "X":
                x_bits[q] = 1
            elif ch == "Y":
                x_bits[q] = 1; z_bits[q] = 1
            elif ch == "Z":
                z_bits[q] = 1
            elif ch != "I":
                raise ValueError(f"bad Pauli character {ch!r} (use IXYZ)")

        # First decide if P commutes with all stabilizers.
        # P commutes with stabilizer (sx, sz) iff
        #     sum(x_bits & sz_i) + sum(z_bits & sx_i)  is even.
        for i in range(n, 2 * n):
            sx = self.tab[i, :n].astype(np.int32)
            sz = self.tab[i, n:2 * n].astype(np.int32)
            anti = (np.sum(x_bits.astype(np.int32) * sz) +
                    np.sum(z_bits.astype(np.int32) * sx)) % 2
            if anti:
                return 0
        # Now P commutes with all stabilizers → P or -P is in the stabilizer
        # group. Reduce P against the destabilizer/stabilizer basis to find
        # the sign. Use scratch row 2N to hold P with phase 0.
        self.tab[2 * n, :n] = x_bits
        self.tab[2 * n, n:2 * n] = z_bits
        self.tab[2 * n, 2 * n] = 0
        # For each destabilizer i: if it anticommutes with our candidate P,
        # the candidate has a "stabilizer-i" component. We multiply scratch by
        # stabilizer i (row i+n) to absorb that component and accumulate phase.
        for i in range(n):
            dx = self.tab[i, :n].astype(np.int32)
            dz = self.tab[i, n:2 * n].astype(np.int32)
            anti = (np.sum(x_bits.astype(np.int32) * dz) +
                    np.sum(z_bits.astype(np.int32) * dx)) % 2
            if anti:
                self._rowsum(2 * n, i + n)
        # After reduction, scratch row's X/Z bits should be all zero.
        # The phase bit gives the sign.
        if int(self.tab[2 * n, :2 * n].sum()) != 0:
            # Numerical safety net — shouldn't happen for well-formed inputs.
            return 0
        return -1 if self.tab[2 * n, 2 * n] else 1

    # ---- verification helper (small N only) --------------------------------

    def to_dense(self) -> np.ndarray:
        """Reconstruct the dense state vector by iteratively applying
        +1-eigenspace projectors of each stabilizer.

        Tries starting from each computational basis state until one has
        nonzero overlap with the stabilizer subspace -- guaranteed to find
        such a basis state since the stabilizer subspace is 1-dimensional.

        Use only for small N (<= ~20); cost is O(N · 4^N) worst-case and
        is meant only for verifying against the dense engine.
        """
        from .gates import I2, X, Y, Z
        n = self.n
        paulis = {(0, 0): I2, (1, 0): X, (0, 1): Z, (1, 1): Y}
        dim = 2 ** n

        # Pre-build the stabilizer matrices (one-time cost).
        S_mats: list[np.ndarray] = []
        for i in range(n, 2 * n):
            S = np.array([[1.0]], dtype=np.complex128)
            for q in range(n):
                x = int(self.tab[i, q]); z = int(self.tab[i, n + q])
                S = np.kron(S, paulis[(x, z)])
            if self.tab[i, 2 * n]:
                S = -S
            S_mats.append(S)

        # Find any computational basis state that has nonzero overlap with
        # the stabilizer subspace, then project it onto that subspace.
        for start in range(dim):
            psi = np.zeros(dim, dtype=np.complex128); psi[start] = 1.0
            for S in S_mats:
                psi = (psi + S @ psi) / 2
            nrm = np.linalg.norm(psi)
            if nrm > 1e-10:
                return psi / nrm
        raise RuntimeError("no computational basis state has nonzero overlap "
                           "with the stabilizer subspace (impossible)")

    # ---- internal ----------------------------------------------------------

    def _check_q(self, q: int) -> None:
        if not (0 <= q < self.n):
            raise IndexError(f"qubit {q} out of range [0, {self.n})")
